config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    render :book_comments
    #redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = BookComment.find(params[:id])
    book_comment.destroy
    render :book_comments
    #redirect_to request.referer
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end


end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_count.html.erb
コメント数: <%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
  <%= f.text_area :comment %>
  <%= f.submit "送信する" %>
<% end %>

app/views/book_comments/_index.html.erb
<% book.book_comments.each do |book_comment| %>
  <table>
  <tr>
    <td>
      <%= image_tag book_comment.user.get_profile_image, size:'100x100' %></br>
      <%= link_to book_comment.user.name, user_path(book_comment.id) %>
    </td>
    <td><%= book_comment.comment %></td>
    <td>
      <% if book_comment.user == current_user %>
        <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger" %>
      <% end %>
    </td>
  </tr>
  </table>
<% end %>

app/views/book_comments/book_comments.js.erb
$(".comments-count").html("コメント数: <%= @book.book_comments.count %>");
<!--id="comments_areaにをrenderで指定した部分テンプレートに更新-->
$("#new-comment").html("<%= j(render 'book_comments/index', book: @book) %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');

app/views/book_comments/index.js.erb
<!--id="comments_areaにをrenderで指定した部分テンプレートに更新-->
$("#comments_area").html("<%= j(render 'index', book: @book, book_comment: @book_comment) %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');